### ISSUE TITLE
Dashboard Add Block

### ISSUE THREAD

**Issue by TheKitty** [adafruit/io-issues#3] opened 2015-01-31 18:25 UTC
Once a block is added, it does not show up immediately on the screen.  If the dashboard being built is being refreshed, then the block shows up.

**Comment by jwcooper** [comment] 2015-03-20 16:34
Can you still reproduce this? I'm not able to. Is it a specific block this happens to?

Thanks!

**Comment by jwcooper** [comment] 2015-06-02 21:18
I'm going to close this, as there has been a lot of changes to the dashboard since this issue was opened, and I'm unable to reproduce it. We can re-open if it appears again.

**Closed by jwcooper** 2015-06-02 21:18 UTC
