### ISSUE TITLE
Timestamps don't pad with zeroes

### ISSUE THREAD

**Issue by milkey-mouse** [adafruit/io-issues#89] opened 2015-12-21 21:04 UTC
In the stream block (and the others as far as I can tell) times that only have one digit are rendering like:

    1:1:9

when they should be rendering like

    1:01:09

or maybe even:

    01:01:09

You just need to pad the timestamps with zeroes at the beginning to make sure they are two digits.

**Comment by andreavalle** [comment] 2016-01-30 09:23
Looks like a duplicate of #82

**Comment by jwcooper** [comment] 2016-04-05 16:37
Indeed a duplicate, closing. Thank you though!

**Closed by jwcooper** 2016-04-05 16:37 UTC
