### ISSUE TITLE
Can not get MQTT.fx to work on my Windows 7 PC, might be intertwined with other problems concerning digital_in.ino

### ISSUE THREAD

**Issue by mtneco48** [adafruit/io-issues#54] opened 2015-10-07 21:28 UTC
Followed everything required on educational layout Welcome to the Home of MQTT.fx and set up Desktop MQTT Client for AdaFruit.io. The program connects to the broker address as shown by the green light and I hit publish button and set up mtneco48/feeds/text like it says to do, then I enter a bit of text into the big empty block below.... The Publish button turns blue and I push it to send the text info that I wrote just like the Lady Ada shows. But he text that I wrote never gets to or changes my feed,text, while I am watching my Dashboard, New Text which is linked to the feed???

Doesn't seem like my io.adafruit is set up to accept my Account or AIO Id? Why won't the system change the text feed???

**Comment by toddtreece** [comment] 2015-10-08 13:28
@mtneco48 try downloading and installing [the latest copy of nmap](https://nmap.org/dist/nmap-6.49BETA5-setup-xp.exe), and then start a nmap scan with the following command:

```
nmap -p 1883 io.adafruit.com
```
check to make sure that it reports port 1883 as open. you should see output similar to the image below.
![mqtt_port_check](https://cloud.githubusercontent.com/assets/360020/10367469/ade93572-6d9e-11e5-86a9-c3a53bc51728.png)

**Comment by mtneco48** [comment] 2015-10-08 17:30
Todd,

    I downloaded and installed nmap , ran it , inputted the command and got exactly what you your display is showing for both ports 1883 and for 8883. Went to MQTT.fx and transmitted a text feed input , and still no change on my dashboard New Text for  the text feed that i Published???

   I can change the text feed data within adafruit.com , but can not make changes to it externally by way of MQTT either y MQTT.fx or by digital_in.ino or digital_out.ino via MQTT.?
But if I use my AIO id with Adafruit IO REST API I can change the text feed by sending it new JSON data stream and it accepts it!

   I don't understand why my computer will not make connection to io.adafruit.com using cc3000/MQTT or MQTT.fx??

    Any other ideas what I am doing wrong?

    By the way I really appreciate your help!!!   THANK YOU FOR YOUR PATIENCE!!!

Matt

**Comment by toddtreece** [comment] 2015-10-09 16:29
could you take some screenshots of your settings and attach them here? it might help to see how things are setup on your end.

**Comment by mtneco48** [comment] 2015-10-11 00:55
Todd,

   I played with it over the weekend and got the MQTTfx program to work with your system. I erased everything on your end and started again rebuilding everything witha new AIO id. The text Publishing still gave me trouble, but then I used the Subscribe portion by setting up a color feed and adjusting the colors from your io.adafruit, and that started to work!! Thank God! So i went back over to the Publishing function and tried that with text and that started working! So all is well with the MQTTfx program ow communicating with io.adafruit. 

    Tomorrow I will try sending the data with the CC3300 and the digital_in and digital_out programs.

Thanks for your help!

matt

**Comment by toddtreece** [comment] 2015-10-11 14:19
@mtneco48 great! one way to test and make sure it's not a bug on the server is to make two text blocks attached to the same feed on a dashboard and update one via the dashboard. the other should do a live update. sorry for the troubles getting going, and let me know if you still have issues w/ the cc3k

**Comment by toddtreece** [comment] 2015-10-13 15:10
closing this one since the MQTTfx issue seems to be resolved

**Closed by toddtreece** 2015-10-13 15:10 UTC
